// frontend-svelte/src/routes/home/[username]/AccountInfo.svelte
<script>

</script>

    <div class="container">
        <div id="musaic">mus(ai)c</div>
        <div id="ai-powered">an ai-powered music application</div>
        <div id="account-info">account info</div>
        <div id="username-box"></div>
        <div id="change-username">change username</div>
        <div id="password-box"></div>
        <div id="change-password">change password</div>
        <div id="submit-box"></div>
        <div id="submit-text">submit</div>
        <div id="discard-changes">discard changes?</div>
    </div> 
    
<style>
    /* container style */
.container {
    width: 100%;
    height: 100%;
    position: relative;
    background: #CBE5F6;
}

/* musaic text */
#musaic {
    width: 532px;
    height: 145px;
    position: absolute;
    left: 454px;
    top: 68px;
    text-align: center;
    color: #0F3A57;
    font-size: 120px;
    font-weight: 400;
    word-wrap: break-word;
}

/* ai-powered text */
#ai-powered {
    width: 578px;
    height: 36px;
    position: absolute;
    left: 431px;
    top: 213px;
    text-align: center;
    color: #185D8B;
    font-size: 30px;
    font-weight: 400;
    word-wrap: break-word;
}

/* account info text */
#account-info {
    width: 326px;
    height: 67px;
    position: absolute;
    left: 557px;
    top: 291px;
    text-align: center;
    color: #0F3A57;
    font-size: 50px;
    font-family: Inter, sans-serif;
    font-weight: 400;
    word-wrap: break-word;
}

/* username box */
#username-box {
    width: 724px;
    height: 96px;
    position: absolute;
    left: 358px;
    top: 381px;
    background: #63B0E3;
}

/* change username text */
#change-username {
    width: 663px;
    height: 60px;
    position: absolute;
    left: 389px;
    top: 399px;
    text-align: center;
    color: #EEF6FC;
    font-size: 50px;
    font-family: Inter, sans-serif;
    font-weight: 400;
    word-wrap: break-word;
}

/* password box */
#password-box {
    width: 724px;
    height: 96px;
    position: absolute;
    left: 358px;
    top: 527px;
    background: #97CAED;
}

/* change password text */
#change-password {
    width: 663px;
    height: 60px;
    position: absolute;
    left: 389px;
    top: 545px;
    text-align: center;
    color: #185D8B;
    font-size: 50px;
    font-family: Inter, sans-serif;
    font-weight: 400;
    word-wrap: break-word;
}

/* submit box */
#submit-box {
    width: 317px;
    height: 96px;
    position: absolute;
    left: 562px;
    top: 673px;
    background: #3498DB;
}

/* submit text */
#submit-text {
    width: 235px;
    height: 67px;
    position: absolute;
    left: 603px;
    top: 687px;
    text-align: center;
    color: #CBE5F6;
    font-size: 50px;
    font-family: Inter, sans-serif;
    font-weight: 400;
    word-wrap: break-word;
}

/* discard changes text */
#discard-changes {
    width: 532px;
    height: 36px;
    position: absolute;
    left: 454px;
    top: 819px;
    text-align: center;
    color: #0F3A57;
    font-size: 30px;
    font-family: Inter, sans-serif;
    font-weight: 400;
    text-decoration: underline;
    word-wrap: break-word;
}
</style>

// front-end/src/app/accountInfo/page.tsx
export default function AccountInfo() {
	return (
		<div className='w-full h-screen bg-[#CBE5F6] flex flex-col items-center'>
			{/* Title */}
			<div className='text-[120px] font-normal text-[#0F3A57] mt-[68px] text-center'>
				mus(ai)c
			</div>

			{/* Subtitle */}
			<div className='text-[30px] font-normal text-[#185D8B] mt-[20px] text-center'>
				an ai-powered music application
			</div>

			{/* Account Info */}
			<div className='text-[50px] font-normal text-[#0F3A57] text-center absolute center-[557px] top-[291px]'>
				account info
			</div>

			{/* Username Box */}
			<div className='w-[724px] h-[96px] bg-[#63B0E3] absolute center-[358px] top-[381px]' />
			<div className='text-[50px] font-normal text-[#EEF6FC] text-center absolute center-[389px] top-[399px]'>
				change username
			</div>

			{/* Password Box */}
			<div className='w-[724px] h-[96px] bg-[#97CAED] absolute center-[358px] top-[527px]' />
			<div className='text-[50px] font-normal text-[#185D8B] text-center absolute center-[389px] top-[545px]'>
				change password
			</div>

			{/* Submit Button */}
			<div className='w-[317px] h-[96px] bg-[#3498DB] absolute center-[562px] top-[673px]' />
			<div className='text-[50px] font-normal text-[#CBE5F6] text-center absolute center-[603px] top-[687px]'>
				submit
			</div>

			{/* Discard Changes */}
			<div className='text-[30px] font-normal text-[#0F3A57] underline text-center absolute center-[454px] top-[819px]'>
				discard changes?
			</div>
		</div>
	);
}
